/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package btl_detai1;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Peggy
 */
public class NGUOIDUNG extends javax.swing.JFrame {

    /**
     * Creates new form NGUOIDUNG
     */
    private MainForm user;

    public void setUser(MainForm user) {
        this.user = user;
    }

    public NGUOIDUNG() {
        this.setUndecorated(true);
        initComponents();
        jLabel8.setComponentZOrder(jLabel7, 0);
        this.setLocationRelativeTo(null);
    }

    public void getCungHoangDao() {
        String day = txtDay.getText();
        String month = txtMonth.getText();
        if (day.isEmpty() || month.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập ngày và tháng.", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            int dayInt = Integer.parseInt(day);
            int monthInt = Integer.parseInt(month);

            String zodiacSign = getCung(dayInt, monthInt);
            if (zodiacSign != null) {
                ketquaZodiac.setText(zodiacSign);
            }
        } catch (NumberFormatException e) {
            // Hiển thị thông báo nếu nhập vào không phải là số
            JOptionPane.showMessageDialog(null, "Vui lòng nhập số hợp lệ cho ngày và tháng.", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
    }

    private String getCung(int day, int month) {
        if (month < 1 || month > 12) {
            JOptionPane.showMessageDialog(null, "Tháng " + month + " không hợp lệ", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return null;
        }
        int[] ngayvathang = {31, (isLeapYear() ? 29 : 28), 31, 30, 31, 30, 31, 31, 30, 31, 30, 31};
        if (day < 1 || day > ngayvathang[month - 1]) {
            JOptionPane.showMessageDialog(null, "Ngày " + day + "/" + month + " không hợp lệ", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return null;
        }

        if ((month == 1 && day >= 20) || (month == 2 && day <= 18)) {
            return "Cung Bảo Bình";
        } else if ((month == 2 && day >= 19) || (month == 3 && day <= 20)) {
            return "Cung Song Ngư";
        } else if ((month == 3 && day >= 21) || (month == 4 && day <= 19)) {
            return "Cung Bạch Dương";
        } else if ((month == 4 && day >= 20) || (month == 5 && day <= 20)) {
            return "Cung Kim Ngưu";
        } else if ((month == 5 && day >= 21) || (month == 6 && day <= 20)) {
            return "Cung Song Tử";
        } else if ((month == 6 && day >= 21) || (month == 7 && day <= 22)) {
            return "Cung Cự Giải";
        } else if ((month == 7 && day >= 23) || (month == 8 && day <= 22)) {
            return "Cung Sư Tử";
        } else if ((month == 8 && day >= 23) || (month == 9 && day <= 22)) {
            return "Cung Xử Nữ";
        } else if ((month == 9 && day >= 23) || (month == 10 && day <= 22)) {
            return "Cung Thiên Bình";
        } else if ((month == 10 && day >= 23) || (month == 11 && day <= 21)) {
            return "Cung Thiên Yết";
        } else if ((month == 11 && day >= 22) || (month == 12 && day <= 21)) {
            return "Cung Nhân Mã";
        } else if ((month == 12 && day >= 22) || (month == 1 && day <= 19)) {
            return "Cung Ma Kết";
        } else {
            JOptionPane.showMessageDialog(null, "Ngày " + day + "/" + month + " không hợp lệ", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return null;
        }
    }

    private boolean isLeapYear() {
        int year = java.time.Year.now().getValue(); // Lấy năm hiện tại
        return (year % 4 == 0 && year % 100 != 0) || (year % 400 == 0); // true
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDay = new javax.swing.JTextField();
        txtMonth = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ketquaZodiac = new javax.swing.JLabel();
        checkCung = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        BACK = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/khungUSER.png"))); // NOI18N

        jLabel1.setText("Ngày");

        jLabel2.setText("Tháng");

        jLabel3.setText("Năm");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("YÊU CẦU NHẬP ĐẦY ĐỦ THÔNG TIN");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("KẾT QUẢ:");

        ketquaZodiac.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ketquaZodiac.setForeground(new java.awt.Color(0, 0, 204));

        checkCung.setText("Check");
        checkCung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCungActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/background-NGUOIDUNG.png"))); // NOI18N

        BACK.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BACK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/back.png"))); // NOI18N
        BACK.setText("BACK");
        BACK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BACKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BACKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BACKMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Xem chi tiết");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(BACK, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel5))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addComponent(jLabel2)
                .addGap(47, 47, 47)
                .addComponent(jLabel3))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(txtMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(checkCung))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel6)
                .addGap(17, 17, 17)
                .addComponent(ketquaZodiac, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel8)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel7))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(BACK, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkCung))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ketquaZodiac, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)))
            .addComponent(jLabel8)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkCungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCungActionPerformed
        getCungHoangDao();
    }//GEN-LAST:event_checkCungActionPerformed

    private void BACKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKMouseEntered
        BACK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/back-HOVER.png")));
    }//GEN-LAST:event_BACKMouseEntered

    private void BACKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKMouseExited
        BACK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/back.png")));
    }//GEN-LAST:event_BACKMouseExited

    private void BACKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKMouseClicked
        this.dispose();
    }//GEN-LAST:event_BACKMouseClicked

    public String getLBLRes() {
        return ketquaZodiac.getText();
    }

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        String zodiacSign = ketquaZodiac.getText();
        if (!zodiacSign.isEmpty()) {
            MOTACUNG motaCung = new MOTACUNG(zodiacSign);
            motaCung.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Vui lòng kiểm tra ngày tháng và nhập đầy đủ thông tin.", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NGUOIDUNG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NGUOIDUNG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NGUOIDUNG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NGUOIDUNG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NGUOIDUNG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BACK;
    private javax.swing.JButton checkCung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel ketquaZodiac;
    private javax.swing.JTextField txtDay;
    private javax.swing.JTextField txtMonth;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables

}
