/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package btl_detai1;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Peggy
 */
public class NGUOIDUNG extends javax.swing.JFrame {

    /**
     * Creates new form NGUOIDUNG
     */
    private MainForm user;

    public void setUser(MainForm user) {
        this.user = user;
    }

    public NGUOIDUNG() {
        this.setUndecorated(true);
        initComponents();
        jLabel8.setComponentZOrder(jLabel7, 0);
        jLabel8.setComponentZOrder(checkCung, 0);
        jLabel8.setComponentZOrder(BACK, 0);
        jLabel8.setComponentZOrder(jLabel4, 0);
        this.setLocationRelativeTo(null);
    }

    public void getCungHoangDao() {
        String day = txtDay.getText();
        String month = txtMonth.getText();
        if (day.isEmpty() || month.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập ngày và tháng.", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            int dayInt = Integer.parseInt(day);
            int monthInt = Integer.parseInt(month);

            String zodiacSign = getCung(dayInt, monthInt);
            if (zodiacSign != null) {
                ketquaZodiac.setText(zodiacSign);
            }
        } catch (NumberFormatException e) {
            // Hiển thị thông báo nếu nhập vào không phải là số
            JOptionPane.showMessageDialog(null, "Vui lòng nhập số hợp lệ cho ngày và tháng.", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
    }

    private String getCung(int day, int month) {
        if (month < 1 || month > 12) {
            JOptionPane.showMessageDialog(null, "Tháng " + month + " không hợp lệ", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return null;
        }
        int[] ngayvathang = {31, (isLeapYear() ? 29 : 28), 31, 30, 31, 30, 31, 31, 30, 31, 30, 31};
        if (day < 1 || day > ngayvathang[month - 1]) {
            JOptionPane.showMessageDialog(null, "Ngày " + day + "/" + month + " không hợp lệ", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return null;
        }

        if ((month == 1 && day >= 20) || (month == 2 && day <= 18)) {
            return "Cung Bảo Bình";
        } else if ((month == 2 && day >= 19) || (month == 3 && day <= 20)) {
            return "Cung Song Ngư";
        } else if ((month == 3 && day >= 21) || (month == 4 && day <= 19)) {
            return "Cung Bạch Dương";
        } else if ((month == 4 && day >= 20) || (month == 5 && day <= 20)) {
            return "Cung Kim Ngưu";
        } else if ((month == 5 && day >= 21) || (month == 6 && day <= 20)) {
            return "Cung Song Tử";
        } else if ((month == 6 && day >= 21) || (month == 7 && day <= 22)) {
            return "Cung Cự Giải";
        } else if ((month == 7 && day >= 23) || (month == 8 && day <= 22)) {
            return "Cung Sư Tử";
        } else if ((month == 8 && day >= 23) || (month == 9 && day <= 22)) {
            return "Cung Xử Nữ";
        } else if ((month == 9 && day >= 23) || (month == 10 && day <= 22)) {
            return "Cung Thiên Bình";
        } else if ((month == 10 && day >= 23) || (month == 11 && day <= 21)) {
            return "Cung Thiên Yết";
        } else if ((month == 11 && day >= 22) || (month == 12 && day <= 21)) {
            return "Cung Nhân Mã";
        } else if ((month == 12 && day >= 22) || (month == 1 && day <= 19)) {
            return "Cung Ma Kết";
        } else {
            JOptionPane.showMessageDialog(null, "Ngày " + day + "/" + month + " không hợp lệ", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return null;
        }
    }

    private boolean isLeapYear() {
        int year = java.time.Year.now().getValue(); // Lấy năm hiện tại
        return (year % 4 == 0 && year % 100 != 0) || (year % 400 == 0); // true
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDay = new javax.swing.JTextField();
        txtMonth = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ketquaZodiac = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BACK = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        checkCung = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/khungUSER.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jLabel1.setText("Ngày");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        jLabel2.setText("Tháng");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, -1));

        jLabel3.setText("Năm");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));
        getContentPane().add(txtDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 45, -1));
        getContentPane().add(txtMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 47, -1));
        getContentPane().add(txtYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 61, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("YÊU CẦU NHẬP ĐẦY ĐỦ THÔNG TIN");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("KẾT QUẢ:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, 20));

        ketquaZodiac.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ketquaZodiac.setForeground(new java.awt.Color(0, 0, 204));
        getContentPane().add(ketquaZodiac, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 170, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/background-NGUOIDUNG.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        BACK.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BACK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/back.png"))); // NOI18N
        BACK.setText("BACK");
        BACK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BACKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BACKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BACKMouseExited(evt);
            }
        });
        getContentPane().add(BACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 90, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Xem chi tiết");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 70, -1));

        checkCung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/check.png"))); // NOI18N
        checkCung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkCungMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                checkCungMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                checkCungMouseExited(evt);
            }
        });
        getContentPane().add(checkCung, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BACKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKMouseEntered
        BACK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/back-HOVER.png")));
    }//GEN-LAST:event_BACKMouseEntered

    private void BACKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKMouseExited
        BACK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/back.png")));
    }//GEN-LAST:event_BACKMouseExited

    private void BACKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKMouseClicked
        this.dispose();
    }//GEN-LAST:event_BACKMouseClicked

    public String getLBLRes() {
        return ketquaZodiac.getText();
    }

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        String zodiacSign = ketquaZodiac.getText();
        if (!zodiacSign.isEmpty()) {
            MOTACUNG motaCung = new MOTACUNG(zodiacSign);
            Timer timer = new Timer(20, null); // Create a timer to update the opacity
            timer.addActionListener(new ActionListener() {
                float opacity = 0f; // Starting opacity

                @Override
                public void actionPerformed(ActionEvent e) {
                    opacity += 0.05f; // Increase opacity
                    if (opacity >= 1f) {
                        opacity = 1f;
                        timer.stop(); // Stop the timer once fully visible
                    }
                    motaCung.setOpacity(opacity); // Set the new opacity
                }
            });

            timer.start(); // Start the timer
            motaCung.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Vui lòng kiểm tra ngày tháng và nhập đầy đủ thông tin.", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void checkCungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkCungMouseClicked
        getCungHoangDao();
    }//GEN-LAST:event_checkCungMouseClicked

    private void checkCungMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkCungMouseEntered
        checkCung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/check-HOVER.png")));
    }//GEN-LAST:event_checkCungMouseEntered

    private void checkCungMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkCungMouseExited
        checkCung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/check.png")));
    }//GEN-LAST:event_checkCungMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NGUOIDUNG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NGUOIDUNG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NGUOIDUNG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NGUOIDUNG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NGUOIDUNG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BACK;
    private javax.swing.JLabel checkCung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel ketquaZodiac;
    private javax.swing.JTextField txtDay;
    private javax.swing.JTextField txtMonth;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables

}
